name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      env:
        TARGETARCH: amd64
      run: |
        docker build .  --tag ghcr.io/warren-ru/trex_exporter:latest
        docker push ghcr.io/warren-ru/trex_exporter:latest
      
