on:
  push:
    tags:
      - "v*"

name: Publish
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

  build:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ["amd64", "arm"]
    steps:
      - name: Version Info
        id: version_info
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - uses: actions/checkout@v2
      - run: go build -a -installsuffix cgo -o bin/trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }} -ldflags "-X github.com/dennisstritzke/trex_exporter/cmd.Version=$TREX_EXPORTER_VERSION"
        env:
          TREX_EXPORTER_VERSION: ${{ steps.version_info.outputs.VERSION }}
          GOOS: linux
          GOARCH: ${{ matrix.architecture }}
          CGO_ENABLED: 0

      - name: Create release archive
        id: create_release_archive
        env:
          TREX_EXPORTER_VERSION: ${{ steps.version_info.outputs.VERSION }}
        run: |
          mkdir -p assets/trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }}
          mv bin/trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }} assets/trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }}

          tar czvf assets/trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }}.tar.gz -C assets trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }}
          echo ::set-output name=archive_name::trex_exporter-$TREX_EXPORTER_VERSION.linux-${{ matrix.architecture }}.tar.gz

      - name: Upload release archives
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: assets/${{ steps.create_release_archive.outputs.archive_name }}
          asset_name: ${{ steps.create_release_archive.outputs.archive_name }}
          asset_content_type: application/tar+gzip

      - uses: actions/upload-artifact@v2
        with:
          name: assets
          path: assets/

  checksums:
    needs: [create_release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download build arttfacts
        uses: actions/download-artifact@v2
        with:
          name: assets
          path: assets/

      - name: Create checksum file
        run: sha256sum assets/*.tar.gz > assets/sha256sums.txt

      - name: Upload release archives
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: assets/sha256sums.txt
          asset_name: sha256sums.txt
          asset_content_type: text/plain